DROP TABLE Clubs;
CREATE TABLE Clubs(
TID VARCHAR(10) PRIMARY KEY,
Club VARCHAR(100)
);

INSERT INTO Clubs VALUES ('T000', "No Team Exists"); 
INSERT INTO Clubs VALUES ('T001', "1. FC Kaiserslautern"); 
INSERT INTO Clubs VALUES ('T002', "1. FC Koln"); 
INSERT INTO Clubs VALUES ('T003', "1. FC Nurnberg"); 
INSERT INTO Clubs VALUES ('T004', "1. FSV Mainz 05"); 
INSERT INTO Clubs VALUES ('T005', "1899 Hoffenheim"); 
INSERT INTO Clubs VALUES ('T006', "Almeria"); 
INSERT INTO Clubs VALUES ('T007', "Arsenal"); 
INSERT INTO Clubs VALUES ('T008', "Aston Villa"); 
INSERT INTO Clubs VALUES ('T009', "Athletic Bilbao"); 
INSERT INTO Clubs VALUES ('T010', "Atletico Madrid"); 
INSERT INTO Clubs VALUES ('T011', "Barcelona"); 
INSERT INTO Clubs VALUES ('T012', "Bayer Leverkusen"); 
INSERT INTO Clubs VALUES ('T013', "Bayern Munchen"); 
INSERT INTO Clubs VALUES ('T014', "Betis"); 
INSERT INTO Clubs VALUES ('T015', "Birmingham"); 
INSERT INTO Clubs VALUES ('T016', "Blackburn Rovers"); 
INSERT INTO Clubs VALUES ('T017', "Blackpool"); 
INSERT INTO Clubs VALUES ('T018', "Bolton Wanderers"); 
INSERT INTO Clubs VALUES ('T019', "Borussia Dortmund"); 
INSERT INTO Clubs VALUES ('T020', "Borussia Monchengladbach"); 
INSERT INTO Clubs VALUES ('T021', "Cardiff City"); 
INSERT INTO Clubs VALUES ('T022', "Celta Vigo"); 
INSERT INTO Clubs VALUES ('T023', "Chelsea"); 
INSERT INTO Clubs VALUES ('T024', "Crystal Palace"); 
INSERT INTO Clubs VALUES ('T025', "Deportivo La Coruna"); 
INSERT INTO Clubs VALUES ('T026', "Eintracht Braunschweig"); 
INSERT INTO Clubs VALUES ('T027', "Eintracht Frankfurt"); 
INSERT INTO Clubs VALUES ('T028', "Elche"); 
INSERT INTO Clubs VALUES ('T029', "Espanyol"); 
INSERT INTO Clubs VALUES ('T030', "Everton"); 
INSERT INTO Clubs VALUES ('T031', "FC Augsburg"); 
INSERT INTO Clubs VALUES ('T032', "FC Schalke 04"); 
INSERT INTO Clubs VALUES ('T033', "FC St. Pauli"); 
INSERT INTO Clubs VALUES ('T034', "Fortuna Dusseldorf"); 
INSERT INTO Clubs VALUES ('T035', "Fulham"); 
INSERT INTO Clubs VALUES ('T036', "Getafe"); 
INSERT INTO Clubs VALUES ('T037', "Granada"); 
INSERT INTO Clubs VALUES ('T038', "Hamburger SV"); 
INSERT INTO Clubs VALUES ('T039', "Hannover 96"); 
INSERT INTO Clubs VALUES ('T040', "Hercules"); 
INSERT INTO Clubs VALUES ('T041', "Hertha BSC"); 
INSERT INTO Clubs VALUES ('T042', "Hull City"); 
INSERT INTO Clubs VALUES ('T043', "Levante"); 
INSERT INTO Clubs VALUES ('T044', "Liverpool"); 
INSERT INTO Clubs VALUES ('T045', "Malaga"); 
INSERT INTO Clubs VALUES ('T046', "Mallorca"); 
INSERT INTO Clubs VALUES ('T047', "Manchester City"); 
INSERT INTO Clubs VALUES ('T048', "Manchester United"); 
INSERT INTO Clubs VALUES ('T049', "Newcastle United"); 
INSERT INTO Clubs VALUES ('T050', "Norwich"); 
INSERT INTO Clubs VALUES ('T051', "Norwich City"); 
INSERT INTO Clubs VALUES ('T052', "Osasuna"); 
INSERT INTO Clubs VALUES ('T053', "Queens Park Rangers"); 
INSERT INTO Clubs VALUES ('T054', "Racing Santander"); 
INSERT INTO Clubs VALUES ('T055', "Rayo Vallecano"); 
INSERT INTO Clubs VALUES ('T056', "Reading"); 
INSERT INTO Clubs VALUES ('T057', "Real Madrid"); 
INSERT INTO Clubs VALUES ('T058', "Real Sociedad"); 
INSERT INTO Clubs VALUES ('T059', "SC Freiburg"); 
INSERT INTO Clubs VALUES ('T060', "Sevilla"); 
INSERT INTO Clubs VALUES ('T061', "Southampton"); 
INSERT INTO Clubs VALUES ('T062', "Sporting Gijon"); 
INSERT INTO Clubs VALUES ('T063', "SpVgg Greuther Fuerth"); 
INSERT INTO Clubs VALUES ('T064', "Stoke City"); 
INSERT INTO Clubs VALUES ('T065', "Sunderland"); 
INSERT INTO Clubs VALUES ('T066', "Swansea City"); 
INSERT INTO Clubs VALUES ('T067', "Tottenham Hotspur"); 
INSERT INTO Clubs VALUES ('T068', "Valencia"); 
INSERT INTO Clubs VALUES ('T069', "Valladolid"); 
INSERT INTO Clubs VALUES ('T070', "VfB Stuttgart"); 
INSERT INTO Clubs VALUES ('T071', "VfL Wolfsburg"); 
INSERT INTO Clubs VALUES ('T072', "Villarreal"); 
INSERT INTO Clubs VALUES ('T073', "Werder Bremen"); 
INSERT INTO Clubs VALUES ('T074', "West Bromwich"); 
INSERT INTO Clubs VALUES ('T075', "West Ham United"); 
INSERT INTO Clubs VALUES ('T076', "Wigan Athletic"); 
INSERT INTO Clubs VALUES ('T077', "Wolverhampton Wanderers"); 
INSERT INTO Clubs VALUES ('T078', "Zaragoza");
INSERT INTO Clubs VALUES ('T079', "VfL Bochum");
INSERT INTO Clubs VALUES ('T080', "Portsmouth");
INSERT INTO Clubs VALUES ('T081', "Tenerife");
INSERT INTO Clubs VALUES ('T082', "Xerez");
