DROP TABLE Club_original;
CREATE TABLE Club_original(
TID VARCHAR(10) NOT NULL,
Club_original VARCHAR(100) NOT NULL
);

INSERT INTO Club_original VALUES ('T008', "Aston Villa"); 
INSERT INTO Club_original VALUES ('T006', "América"); 
INSERT INTO Club_original VALUES ('T007', "Arsenal"); 
INSERT INTO Club_original VALUES ('T049', "Newcastle U"); 
INSERT INTO Club_original VALUES ('T027', "Eintracht Frankfurt"); 
INSERT INTO Club_original VALUES ('T072', "Villarreal"); 
INSERT INTO Club_original VALUES ('T013', "Bayern Munich"); 
INSERT INTO Club_original VALUES ('T057', "Real Madrid"); 
INSERT INTO Club_original VALUES ('T035', "Fulham"); 
INSERT INTO Club_original VALUES ('T036', "Getafe"); 
INSERT INTO Club_original VALUES ('T014', "Betis"); 
INSERT INTO Club_original VALUES ('T011', "Barcelona"); 
INSERT INTO Club_original VALUES ('T077', "Wolverhampton W"); 
INSERT INTO Club_original VALUES ('T012', "Bayer Leverkusen"); 
INSERT INTO Club_original VALUES ('T078', "Zaragoza"); 
INSERT INTO Club_original VALUES ('T056', "Reading"); 
INSERT INTO Club_original VALUES ('T075', "West Ham U"); 
INSERT INTO Club_original VALUES ('T032', "Schalke"); 
INSERT INTO Club_original VALUES ('T010', "Atlético Madrid"); 
INSERT INTO Club_original VALUES ('T076', "Wigan Ath"); 
INSERT INTO Club_original VALUES ('T073', "Werder Bremen"); 
INSERT INTO Club_original VALUES ('T052', "Osasuna"); 
INSERT INTO Club_original VALUES ('T030', "Everton"); 
INSERT INTO Club_original VALUES ('T019', "Borussia Dortmund"); 
INSERT INTO Club_original VALUES ('T039', "Hannover 96"); 
INSERT INTO Club_original VALUES ('T015', "Birmingham C"); 
INSERT INTO Club_original VALUES ('T016', "Blackburn R"); 
INSERT INTO Club_original VALUES ('T038', "Hamburg II"); 
INSERT INTO Club_original VALUES ('T060', "Sevilla"); 
INSERT INTO Club_original VALUES ('T061', "Southampton"); 
INSERT INTO Club_original VALUES ('T068', "Valencia"); 
INSERT INTO Club_original VALUES ('T024', "Crystal Palace"); 
INSERT INTO Club_original VALUES ('T025', "Deportivo La Coruña"); 
INSERT INTO Club_original VALUES ('T047', "Manchester U"); 
INSERT INTO Club_original VALUES ('T000', "Shakhtar Donetsk"); 
INSERT INTO Club_original VALUES ('T044', "Liverpool"); 
INSERT INTO Club_original VALUES ('T023', "Chelsea"); 
INSERT INTO Club_original VALUES ('T067', "Tottenham H"); 
INSERT INTO Club_original VALUES ('T020', "B Mönchengladbach"); 
INSERT INTO Club_original VALUES ('T042', "Hull C"); 
INSERT INTO Club_original VALUES ('T062', "Sporting Braga"); 
INSERT INTO Club_original VALUES ('T041', "Hertha Berlin"); 
INSERT INTO Club_original VALUES ('T008', "Aston Villa"); 
INSERT INTO Club_original VALUES ('T009', "Athletic Bilbao"); 
INSERT INTO Club_original VALUES ('T006', "América"); 
INSERT INTO Club_original VALUES ('T007', "Arsenal"); 
INSERT INTO Club_original VALUES ('T029', "Espanyol"); 
INSERT INTO Club_original VALUES ('T049', "Newcastle U Jets"); 
INSERT INTO Club_original VALUES ('T005', "1899 Hoffenheim"); 
INSERT INTO Club_original VALUES ('T027', "Eintracht Frankfurt"); 
INSERT INTO Club_original VALUES ('T072', "Villarreal"); 
INSERT INTO Club_original VALUES ('T013', "Bayern Munich"); 
INSERT INTO Club_original VALUES ('T035', "Fulham"); 
INSERT INTO Club_original VALUES ('T057', "Real Madrid"); 
INSERT INTO Club_original VALUES ('T036', "Getafe"); 
INSERT INTO Club_original VALUES ('T014', "Betis"); 
INSERT INTO Club_original VALUES ('T058', "Real Sociedad"); 
INSERT INTO Club_original VALUES ('T011', "Barcelona"); 
INSERT INTO Club_original VALUES ('T077', "Wolverhampton W"); 
INSERT INTO Club_original VALUES ('T012', "Bayer Leverkusen"); 
INSERT INTO Club_original VALUES ('T056', "Reading"); 
INSERT INTO Club_original VALUES ('T078', "Zaragoza"); 
INSERT INTO Club_original VALUES ('T075', "West Ham U"); 
INSERT INTO Club_original VALUES ('T010', "Atlético Madrid"); 
INSERT INTO Club_original VALUES ('T054', "Racing Santander"); 
INSERT INTO Club_original VALUES ('T032', "Schalke"); 
INSERT INTO Club_original VALUES ('T076', "Wigan Ath"); 
INSERT INTO Club_original VALUES ('T073', "Werder Bremen"); 
INSERT INTO Club_original VALUES ('T030', "Everton"); 
INSERT INTO Club_original VALUES ('T019', "Borussia Dortmund"); 
INSERT INTO Club_original VALUES ('T039', "Hannover 96"); 
INSERT INTO Club_original VALUES ('T016', "Blackburn R"); 
INSERT INTO Club_original VALUES ('T060', "Sevilla"); 
INSERT INTO Club_original VALUES ('T068', "Valencia"); 
INSERT INTO Club_original VALUES ('T046', "Mallorca"); 
INSERT INTO Club_original VALUES ('T047', "Manchester C"); 
INSERT INTO Club_original VALUES ('T025', "Deportivo La Coruña"); 
INSERT INTO Club_original VALUES ('T069', "Valladolid"); 
INSERT INTO Club_original VALUES ('T000', "Basel"); 
INSERT INTO Club_original VALUES ('T044', "Liverpool"); 
INSERT INTO Club_original VALUES ('T023', "Chelsea"); 
INSERT INTO Club_original VALUES ('T067', "Tottenham H"); 
INSERT INTO Club_original VALUES ('T045', "Málaga"); 
INSERT INTO Club_original VALUES ('T020', "B Mönchengladbach"); 
INSERT INTO Club_original VALUES ('T042', "Hull C"); 
INSERT INTO Club_original VALUES ('T064', "Stoke C"); 
INSERT INTO Club_original VALUES ('T065', "Sunderland"); 
INSERT INTO Club_original VALUES ('T062', "Sporting CP"); 
INSERT INTO Club_original VALUES ('T041', "Hertha Berlin"); 
INSERT INTO Club_original VALUES ('T028', "Elche"); 
INSERT INTO Club_original VALUES ('T029', "Espanyol"); 
INSERT INTO Club_original VALUES ('T026', "Eintracht Braunschweig"); 
INSERT INTO Club_original VALUES ('T027', "Eintracht Frankfurt"); 
INSERT INTO Club_original VALUES ('T072', "Villarreal"); 
INSERT INTO Club_original VALUES ('T035', "Fulham"); 
INSERT INTO Club_original VALUES ('T036', "Getafe"); 
INSERT INTO Club_original VALUES ('T034', "Fortuna Düsseldorf"); 
INSERT INTO Club_original VALUES ('T031', "Augsburg"); 
INSERT INTO Club_original VALUES ('T075', "West Ham U"); 
INSERT INTO Club_original VALUES ('T032', "Schalke"); 
INSERT INTO Club_original VALUES ('T076', "Wigan Ath"); 
INSERT INTO Club_original VALUES ('T030', "Everton"); 
INSERT INTO Club_original VALUES ('T019', "Borussia Dortmund"); 
INSERT INTO Club_original VALUES ('T060', "Sevilla"); 
INSERT INTO Club_original VALUES ('T061', "Southampton"); 
INSERT INTO Club_original VALUES ('T024', "Crystal Palace"); 
INSERT INTO Club_original VALUES ('T068', "Valencia"); 
INSERT INTO Club_original VALUES ('T025', "Deportivo Saprissa"); 
INSERT INTO Club_original VALUES ('T022', "Celta Vigo"); 
INSERT INTO Club_original VALUES ('T066', "Swansea C"); 
INSERT INTO Club_original VALUES ('T023', "Chelsea"); 
INSERT INTO Club_original VALUES ('T067', "Tottenham H"); 
INSERT INTO Club_original VALUES ('T064', "Stoke C"); 
INSERT INTO Club_original VALUES ('T020', "B Mönchengladbach"); 
INSERT INTO Club_original VALUES ('T021', "Cardiff C"); 
INSERT INTO Club_original VALUES ('T065', "Sunderland"); 
INSERT INTO Club_original VALUES ('T062', "Sporting CP"); 
INSERT INTO Club_original VALUES ('T008', "Aston Villa"); 
INSERT INTO Club_original VALUES ('T006', "Almería"); 
INSERT INTO Club_original VALUES ('T007', "Arsenal"); 
INSERT INTO Club_original VALUES ('T049', "Newcastle U"); 
INSERT INTO Club_original VALUES ('T005', "1899 Hoffenheim"); 
INSERT INTO Club_original VALUES ('T050', "Norwich C"); 
INSERT INTO Club_original VALUES ('T057', "Real Madrid"); 
INSERT INTO Club_original VALUES ('T013', "Bayern Munich"); 
INSERT INTO Club_original VALUES ('T058', "Real Sociedad"); 
INSERT INTO Club_original VALUES ('T011', "Barcelona"); 
INSERT INTO Club_original VALUES ('T012', "Bayer Leverkusen"); 
INSERT INTO Club_original VALUES ('T053', "QPR"); 
INSERT INTO Club_original VALUES ('T010', "Atlético Madrid"); 
INSERT INTO Club_original VALUES ('T052', "Osasuna"); 
INSERT INTO Club_original VALUES ('T039', "Hannover 96"); 
INSERT INTO Club_original VALUES ('T037', "Granada"); 
INSERT INTO Club_original VALUES ('T046', "Mallorca"); 
INSERT INTO Club_original VALUES ('T047', "Manchester U"); 
INSERT INTO Club_original VALUES ('T000', "Busan I'Park"); 
INSERT INTO Club_original VALUES ('T044', "Liverpool"); 
INSERT INTO Club_original VALUES ('T042', "Hull C"); 
INSERT INTO Club_original VALUES ('T043', "Levante"); 
INSERT INTO Club_original VALUES ('T041', "Hertha Berlin"); 
INSERT INTO Club_original VALUES ('T008', "Aston Villa"); 
INSERT INTO Club_original VALUES ('T006', "América"); 
INSERT INTO Club_original VALUES ('T007', "Arsenal"); 
INSERT INTO Club_original VALUES ('T029', "Espanyol"); 
INSERT INTO Club_original VALUES ('T027', "Eintracht Frankfurt"); 
INSERT INTO Club_original VALUES ('T049', "Newcastle U"); 
INSERT INTO Club_original VALUES ('T013', "Bayern Munich"); 
INSERT INTO Club_original VALUES ('T057', "Real Madrid"); 
INSERT INTO Club_original VALUES ('T035', "Fulham"); 
INSERT INTO Club_original VALUES ('T058', "Real Sociedad"); 
INSERT INTO Club_original VALUES ('T014', "Betis"); 
INSERT INTO Club_original VALUES ('T011', "Barcelona"); 
INSERT INTO Club_original VALUES ('T012', "Bayer Leverkusen"); 
INSERT INTO Club_original VALUES ('T075', "West Ham U"); 
INSERT INTO Club_original VALUES ('T032', "Schalke"); 
INSERT INTO Club_original VALUES ('T054', "Racing Santander"); 
INSERT INTO Club_original VALUES ('T010', "Atlético Madrid"); 
INSERT INTO Club_original VALUES ('T073', "Werder Bremen"); 
INSERT INTO Club_original VALUES ('T030', "Everton"); 
INSERT INTO Club_original VALUES ('T019', "Borussia Dortmund"); 
INSERT INTO Club_original VALUES ('T039', "Hannover 96"); 
INSERT INTO Club_original VALUES ('T016', "Blackburn R"); 
INSERT INTO Club_original VALUES ('T060', "Seville"); 
INSERT INTO Club_original VALUES ('T061', "Southampton"); 
INSERT INTO Club_original VALUES ('T068', "Valencia"); 
INSERT INTO Club_original VALUES ('T046', "Mallorca"); 
INSERT INTO Club_original VALUES ('T024', "Crystal Palace"); 
INSERT INTO Club_original VALUES ('T047', "Manchester U"); 
INSERT INTO Club_original VALUES ('T025', "Deportivo Saprissa"); 
INSERT INTO Club_original VALUES ('T069', "Valladolid"); 
INSERT INTO Club_original VALUES ('T000', "Espérance"); 
INSERT INTO Club_original VALUES ('T022', "Celta Vigo"); 
INSERT INTO Club_original VALUES ('T044', "Liverpool"); 
INSERT INTO Club_original VALUES ('T023', "Chelsea"); 
INSERT INTO Club_original VALUES ('T045', "Málaga"); 
INSERT INTO Club_original VALUES ('T067', "Tottenham H"); 
INSERT INTO Club_original VALUES ('T065', "Sunderland"); 
INSERT INTO Club_original VALUES ('T062', "Sporting CP"); 
INSERT INTO Club_original VALUES ('T041', "Hertha Berlin"); 
