DROP TABLE Country_code;
CREATE TABLE Country_code(
NCode VARCHAR(10) NOT NULL,
Country VARCHAR(100) NOT NULL,
CONSTRAINT Nation_ID PRIMARY KEY(NCode, Country)
);

INSERT INTO Country_code VALUES ('AFG', "Afghanistan"); 
INSERT INTO Country_code VALUES ('ALB', "Albania"); 
INSERT INTO Country_code VALUES ('ALG', "Algeria"); 
INSERT INTO Country_code VALUES ('ASA', "American Samoa"); 
INSERT INTO Country_code VALUES ('AND', "Andorra"); 
INSERT INTO Country_code VALUES ('ANG', "Angola"); 
INSERT INTO Country_code VALUES ('AIA', "Anguilla"); 
INSERT INTO Country_code VALUES ('ATG', "Antigua and Barbuda"); 
INSERT INTO Country_code VALUES ('ARG', "Argentina"); 
INSERT INTO Country_code VALUES ('ARM', "Armenia"); 
INSERT INTO Country_code VALUES ('ARU', "Aruba"); 
INSERT INTO Country_code VALUES ('AUS', "Australia"); 
INSERT INTO Country_code VALUES ('AUT', "Austria"); 
INSERT INTO Country_code VALUES ('AZE', "Azerbaijan"); 
INSERT INTO Country_code VALUES ('BAH', "Bahamas"); 
INSERT INTO Country_code VALUES ('BHR', "Bahrain"); 
INSERT INTO Country_code VALUES ('BAN', "Bangladesh"); 
INSERT INTO Country_code VALUES ('BRB', "Barbados"); 
INSERT INTO Country_code VALUES ('BLR', "Belarus"); 
INSERT INTO Country_code VALUES ('BEL', "Belgium"); 
INSERT INTO Country_code VALUES ('BLZ', "Belize"); 
INSERT INTO Country_code VALUES ('BEN', "Benin"); 
INSERT INTO Country_code VALUES ('BER', "Bermuda"); 
INSERT INTO Country_code VALUES ('BHU', "Bhutan"); 
INSERT INTO Country_code VALUES ('BOL', "Bolivia"); 
INSERT INTO Country_code VALUES ('BIH', "Bosnia and Herzegovina"); 
INSERT INTO Country_code VALUES ('BOT', "Botswana"); 
INSERT INTO Country_code VALUES ('BRA', "Brazil"); 
INSERT INTO Country_code VALUES ('BRA', "Brasil"); 
INSERT INTO Country_code VALUES ('VGB', "British Virgin Islands"); 
INSERT INTO Country_code VALUES ('BRU', "Brunei"); 
INSERT INTO Country_code VALUES ('BUL', "Bulgaria"); 
INSERT INTO Country_code VALUES ('BFA', "Burkina Faso"); 
INSERT INTO Country_code VALUES ('BDI', "Burundi"); 
INSERT INTO Country_code VALUES ('CAM', "Cambodia"); 
INSERT INTO Country_code VALUES ('CMR', "Cameroon"); 
INSERT INTO Country_code VALUES ('CAN', "Canada"); 
INSERT INTO Country_code VALUES ('CPV', "Cape Verde"); 
INSERT INTO Country_code VALUES ('CAY', "Cayman Islands"); 
INSERT INTO Country_code VALUES ('CTA', "Central African Republic"); 
INSERT INTO Country_code VALUES ('CHA', "Chad"); 
INSERT INTO Country_code VALUES ('CHI', "Chile"); 
INSERT INTO Country_code VALUES ('CHN', "China PR"); 
INSERT INTO Country_code VALUES ('CHN', "China"); 
INSERT INTO Country_code VALUES ('CHN', "PRC"); 
INSERT INTO Country_code VALUES ('CHN', "People's Republic of China"); 
INSERT INTO Country_code VALUES ('TPE', "Chinese Taipei"); 
INSERT INTO Country_code VALUES ('TPE', "Taiwan"); 
INSERT INTO Country_code VALUES ('TPE', "Republic of China"); 
INSERT INTO Country_code VALUES ('COL', "Colombia"); 
INSERT INTO Country_code VALUES ('COM', "Comoros"); 
INSERT INTO Country_code VALUES ('CGO', "Congo"); 
INSERT INTO Country_code VALUES ('COK', "Cook Islands"); 
INSERT INTO Country_code VALUES ('CRC', "Costa Rica"); 
INSERT INTO Country_code VALUES ('CIV', "Côte d'Ivoire"); 
INSERT INTO Country_code VALUES ('CRO', "Croatia"); 
INSERT INTO Country_code VALUES ('CUB', "Cuba"); 
INSERT INTO Country_code VALUES ('CUW', "Curaçao"); 
INSERT INTO Country_code VALUES ('CYP', "Cyprus"); 
INSERT INTO Country_code VALUES ('CZE', "Czechia"); 
INSERT INTO Country_code VALUES ('CZE', "Czech Republic"); 
INSERT INTO Country_code VALUES ('DEN', "Denmark"); 
INSERT INTO Country_code VALUES ('DJI', "Djibouti"); 
INSERT INTO Country_code VALUES ('DMA', "Dominica"); 
INSERT INTO Country_code VALUES ('DOM', "Dominican Republic"); 
INSERT INTO Country_code VALUES ('COD', "DR Congo"); 
INSERT INTO Country_code VALUES ('ECU', "Ecuador"); 
INSERT INTO Country_code VALUES ('EGY', "Egypt"); 
INSERT INTO Country_code VALUES ('SLV', "El Salvador"); 
INSERT INTO Country_code VALUES ('ENG', "England"); 
INSERT INTO Country_code VALUES ('ENG', "UK"); 
INSERT INTO Country_code VALUES ('ENG', "Britain"); 
INSERT INTO Country_code VALUES ('ENG', "United Kingdom"); 
INSERT INTO Country_code VALUES ('EQG', "Equatorial Guinea"); 
INSERT INTO Country_code VALUES ('ERI', "Eritrea"); 
INSERT INTO Country_code VALUES ('EST', "Estonia"); 
INSERT INTO Country_code VALUES ('ETH', "Ethiopia"); 
INSERT INTO Country_code VALUES ('FRO', "Faroe Islands"); 
INSERT INTO Country_code VALUES ('FIJ', "Fiji"); 
INSERT INTO Country_code VALUES ('FIN', "Finland"); 
INSERT INTO Country_code VALUES ('FRA', "France"); 
INSERT INTO Country_code VALUES ('GAB', "Gabon"); 
INSERT INTO Country_code VALUES ('GAM', "Gambia"); 
INSERT INTO Country_code VALUES ('GEO', "Georgia"); 
INSERT INTO Country_code VALUES ('GER', "Germany"); 
INSERT INTO Country_code VALUES ('GHA', "Ghana"); 
INSERT INTO Country_code VALUES ('GIB', "Gibraltar"); 
INSERT INTO Country_code VALUES ('GRE', "Greece"); 
INSERT INTO Country_code VALUES ('GRN', "Grenada"); 
INSERT INTO Country_code VALUES ('GUM', "Guam"); 
INSERT INTO Country_code VALUES ('GUA', "Guatemala"); 
INSERT INTO Country_code VALUES ('GUI', "Guinea"); 
INSERT INTO Country_code VALUES ('GNB', "Guinea-Bissau"); 
INSERT INTO Country_code VALUES ('GUY', "Guyana"); 
INSERT INTO Country_code VALUES ('HAI', "Haiti"); 
INSERT INTO Country_code VALUES ('HON', "Honduras"); 
INSERT INTO Country_code VALUES ('HKG', "Hong Kong"); 
INSERT INTO Country_code VALUES ('HUN', "Hungary"); 
INSERT INTO Country_code VALUES ('ISL', "Iceland"); 
INSERT INTO Country_code VALUES ('IND', "India"); 
INSERT INTO Country_code VALUES ('IDN', "Indonesia"); 
INSERT INTO Country_code VALUES ('IRN', "Iran"); 
INSERT INTO Country_code VALUES ('IRQ', "Iraq"); 
INSERT INTO Country_code VALUES ('ISR', "Israel"); 
INSERT INTO Country_code VALUES ('ITA', "Italy"); 
INSERT INTO Country_code VALUES ('JAM', "Jamaica"); 
INSERT INTO Country_code VALUES ('JPN', "Japan"); 
INSERT INTO Country_code VALUES ('JPN', "South Korea & Japan"); 
INSERT INTO Country_code VALUES ('JOR', "Jordan"); 
INSERT INTO Country_code VALUES ('KAZ', "Kazakhstan"); 
INSERT INTO Country_code VALUES ('KEN', "Kenya"); 
INSERT INTO Country_code VALUES ('PRK', "Korea DPR");
INSERT INTO Country_code VALUES ('PRK', "North Korea"); 
INSERT INTO Country_code VALUES ('KOR', "Korea Republic");
INSERT INTO Country_code VALUES ('KOR', "South Korea"); 
INSERT INTO Country_code VALUES ('KOR', "Korea"); 
INSERT INTO Country_code VALUES ('KOR', "South Korea & Japan"); 
INSERT INTO Country_code VALUES ('KOR', "Republic of Korea"); 
INSERT INTO Country_code VALUES ('KVX', "Kosovo"); 
INSERT INTO Country_code VALUES ('KUW', "Kuwait"); 
INSERT INTO Country_code VALUES ('KGZ', "Kyrgyzstan"); 
INSERT INTO Country_code VALUES ('LAO', "Laos"); 
INSERT INTO Country_code VALUES ('LVA', "Latvia"); 
INSERT INTO Country_code VALUES ('LIB', "Lebanon"); 
INSERT INTO Country_code VALUES ('LES', "Lesotho"); 
INSERT INTO Country_code VALUES ('LBR', "Liberia"); 
INSERT INTO Country_code VALUES ('LBY', "Libya"); 
INSERT INTO Country_code VALUES ('LIE', "Liechtenstein"); 
INSERT INTO Country_code VALUES ('LTU', "Lithuania"); 
INSERT INTO Country_code VALUES ('LUX', "Luxembourg"); 
INSERT INTO Country_code VALUES ('MAC', "Macau"); 
INSERT INTO Country_code VALUES ('MKD', "FYR Macedonia"); 
INSERT INTO Country_code VALUES ('MAD', "Madagascar"); 
INSERT INTO Country_code VALUES ('MWI', "Malawi"); 
INSERT INTO Country_code VALUES ('MAS', "Malaysia"); 
INSERT INTO Country_code VALUES ('MDV', "Maldives"); 
INSERT INTO Country_code VALUES ('MLI', "Mali"); 
INSERT INTO Country_code VALUES ('MLT', "Malta"); 
INSERT INTO Country_code VALUES ('MTN', "Mauritania"); 
INSERT INTO Country_code VALUES ('MRI', "Mauritius"); 
INSERT INTO Country_code VALUES ('MEX', "Mexico"); 
INSERT INTO Country_code VALUES ('MDA', "Moldova"); 
INSERT INTO Country_code VALUES ('MGL', "Mongolia"); 
INSERT INTO Country_code VALUES ('MNE', "Montenegro"); 
INSERT INTO Country_code VALUES ('MSR', "Montserrat"); 
INSERT INTO Country_code VALUES ('MAR', "Morocco"); 
INSERT INTO Country_code VALUES ('MOZ', "Mozambique"); 
INSERT INTO Country_code VALUES ('MYA', "Myanmar"); 
INSERT INTO Country_code VALUES ('NAM', "Namibia"); 
INSERT INTO Country_code VALUES ('NEP', "Nepal"); 
INSERT INTO Country_code VALUES ('NED', "Netherlands"); 
INSERT INTO Country_code VALUES ('NCL', "New Caledonia"); 
INSERT INTO Country_code VALUES ('NZL', "New Zealand"); 
INSERT INTO Country_code VALUES ('NCA', "Nicaragua"); 
INSERT INTO Country_code VALUES ('NIG', "Niger"); 
INSERT INTO Country_code VALUES ('NGA', "Nigeria"); 
INSERT INTO Country_code VALUES ('NIR', "Northern Ireland"); 
INSERT INTO Country_code VALUES ('NOR', "Norway"); 
INSERT INTO Country_code VALUES ('OMA', "Oman"); 
INSERT INTO Country_code VALUES ('PAK', "Pakistan"); 
INSERT INTO Country_code VALUES ('PLE', "Palestine"); 
INSERT INTO Country_code VALUES ('PAN', "Panama"); 
INSERT INTO Country_code VALUES ('PNG', "Papua New Guinea"); 
INSERT INTO Country_code VALUES ('PAR', "Paraguay"); 
INSERT INTO Country_code VALUES ('PER', "Peru"); 
INSERT INTO Country_code VALUES ('PHI', "Philippines"); 
INSERT INTO Country_code VALUES ('POL', "Poland"); 
INSERT INTO Country_code VALUES ('POR', "Portugal"); 
INSERT INTO Country_code VALUES ('PUR', "Puerto Rico"); 
INSERT INTO Country_code VALUES ('QAT', "Qatar"); 
INSERT INTO Country_code VALUES ('IRL', "Republic of Ireland"); 
INSERT INTO Country_code VALUES ('ROU', "Romania"); 
INSERT INTO Country_code VALUES ('RUS', "Russia"); 
INSERT INTO Country_code VALUES ('RWA', "Rwanda"); 
INSERT INTO Country_code VALUES ('SKN', "Saint Kitts and Nevis"); 
INSERT INTO Country_code VALUES ('LCA', "Saint Lucia"); 
INSERT INTO Country_code VALUES ('VIN', "Saint Vincent and the Grenadines"); 
INSERT INTO Country_code VALUES ('SAM', "Samoa"); 
INSERT INTO Country_code VALUES ('SMR', "San Marino"); 
INSERT INTO Country_code VALUES ('STP', "São Tomé and Príncipe"); 
INSERT INTO Country_code VALUES ('KSA', "Saudi Arabia"); 
INSERT INTO Country_code VALUES ('SCO', "Scotland"); 
INSERT INTO Country_code VALUES ('SEN', "Senegal"); 
INSERT INTO Country_code VALUES ('SRB', "Serbia"); 
INSERT INTO Country_code VALUES ('SEY', "Seychelles"); 
INSERT INTO Country_code VALUES ('SLE', "Sierra Leone"); 
INSERT INTO Country_code VALUES ('SIN', "Singapore"); 
INSERT INTO Country_code VALUES ('SVK', "Slovakia"); 
INSERT INTO Country_code VALUES ('SVN', "Slovenia"); 
INSERT INTO Country_code VALUES ('SOL', "Solomon Islands"); 
INSERT INTO Country_code VALUES ('SOM', "Somalia"); 
INSERT INTO Country_code VALUES ('RSA', "South Africa"); 
INSERT INTO Country_code VALUES ('SSD', "South Sudan"); 
INSERT INTO Country_code VALUES ('ESP', "Spain"); 
INSERT INTO Country_code VALUES ('ESP', "Espanol"); 
INSERT INTO Country_code VALUES ('SRI', "Sri Lanka"); 
INSERT INTO Country_code VALUES ('SUD', "Sudan"); 
INSERT INTO Country_code VALUES ('SUR', "Suriname"); 
INSERT INTO Country_code VALUES ('SWZ', "Swaziland"); 
INSERT INTO Country_code VALUES ('SWE', "Sweden"); 
INSERT INTO Country_code VALUES ('SUI', "Switzerland"); 
INSERT INTO Country_code VALUES ('SYR', "Syria"); 
INSERT INTO Country_code VALUES ('TAH', "Tahiti"); 
INSERT INTO Country_code VALUES ('TJK', "Tajikistan"); 
INSERT INTO Country_code VALUES ('TAN', "Tanzania"); 
INSERT INTO Country_code VALUES ('THA', "Thailand"); 
INSERT INTO Country_code VALUES ('TLS', "Timor-Leste"); 
INSERT INTO Country_code VALUES ('TOG', "Togo"); 
INSERT INTO Country_code VALUES ('TGA', "Tonga"); 
INSERT INTO Country_code VALUES ('TRI', "Trinidad and Tobago"); 
INSERT INTO Country_code VALUES ('TUN', "Tunisia"); 
INSERT INTO Country_code VALUES ('TUR', "Turkey"); 
INSERT INTO Country_code VALUES ('TKM', "Turkmenistan"); 
INSERT INTO Country_code VALUES ('TCA', "Turks and Caicos Islands"); 
INSERT INTO Country_code VALUES ('UGA', "Uganda"); 
INSERT INTO Country_code VALUES ('UKR', "Ukraine"); 
INSERT INTO Country_code VALUES ('UAE', "United Arab Emirates"); 
INSERT INTO Country_code VALUES ('USA', "USA"); 
INSERT INTO Country_code VALUES ('USA', "United States"); 
INSERT INTO Country_code VALUES ('USA', "America"); 
INSERT INTO Country_code VALUES ('URU', "Uruguay"); 
INSERT INTO Country_code VALUES ('VIR', "US Virgin Islands"); 
INSERT INTO Country_code VALUES ('UZB', "Uzbekistan"); 
INSERT INTO Country_code VALUES ('VAN', "Vanuatu"); 
INSERT INTO Country_code VALUES ('VEN', "Venezuela"); 
INSERT INTO Country_code VALUES ('VIE', "Vietnam"); 
INSERT INTO Country_code VALUES ('WAL', "Wales"); 
INSERT INTO Country_code VALUES ('YEM', "Yemen"); 
INSERT INTO Country_code VALUES ('ZAM', "Zambia"); 
INSERT INTO Country_code VALUES ('ZIM', "Zimbabwe"); 
