DROP TABLE Olympic_record;
CREATE TABLE Olympic_record(
Year   VARCHAR(4) NOT NULL,
Rank   VARCHAR(3),
Country   VARCHAR(100) NOT NULL,
NOC VARCHAR(4),
CONSTRAINT recordKey PRIMARY KEY(Year, Country)
);

INSERT INTO Olympic_record VALUES ('1900', '1', "Upton Park FC", 'GBR'); 
INSERT INTO Olympic_record VALUES ('1900', '2', "USFSA", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1900', '3', "Univ. of Brussels", 'MIX'); 
INSERT INTO Olympic_record VALUES ('1904', '1', "Galt Football Club", 'CAN'); 
INSERT INTO Olympic_record VALUES ('1904', '2', "Christian Brothers' College-1", 'USA'); 
INSERT INTO Olympic_record VALUES ('1904', '3', "St. Rose-2", 'USA'); 
INSERT INTO Olympic_record VALUES ('1908', '1', "Great Britain", 'GBR'); 
INSERT INTO Olympic_record VALUES ('1908', '2', "Denmark", 'DEN'); 
INSERT INTO Olympic_record VALUES ('1908', '3', "Netherlands", 'NED'); 
INSERT INTO Olympic_record VALUES ('1908', '4', "Sweden", 'SWE'); 
INSERT INTO Olympic_record VALUES ('1908', '5', "France A-1", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1908', '5', "France B-2", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1912', '1', "Great Britain", 'GBR'); 
INSERT INTO Olympic_record VALUES ('1912', '2', "Denmark", 'DEN'); 
INSERT INTO Olympic_record VALUES ('1912', '3', "Netherlands", 'NED'); 
INSERT INTO Olympic_record VALUES ('1912', '4', "Finland", 'FIN'); 
INSERT INTO Olympic_record VALUES ('1912', '5', "Hungary", 'HUN'); 
INSERT INTO Olympic_record VALUES ('1912', '5', "Norway", 'NOR'); 
INSERT INTO Olympic_record VALUES ('1912', '5', "Austria", 'AUT'); 
INSERT INTO Olympic_record VALUES ('1912', '5', "Russia", 'RUS'); 
INSERT INTO Olympic_record VALUES ('1912', '9', "Germany", 'GER'); 
INSERT INTO Olympic_record VALUES ('1912', '9', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1912', '9', "Sweden", 'SWE'); 
INSERT INTO Olympic_record VALUES ('1920', '1', "Belgium", 'BEL'); 
INSERT INTO Olympic_record VALUES ('1920', '2', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('1920', '3', "Netherlands", 'NED'); 
INSERT INTO Olympic_record VALUES ('1920', '4', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1920', '5', "Norway", 'NOR'); 
INSERT INTO Olympic_record VALUES ('1920', '5', "Sweden", 'SWE'); 
INSERT INTO Olympic_record VALUES ('1920', '7', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1920', '8', "Denmark", 'DEN'); 
INSERT INTO Olympic_record VALUES ('1920', '8', "Egypt", 'EGY'); 
INSERT INTO Olympic_record VALUES ('1920', '8', "Great Britain", 'GBR'); 
INSERT INTO Olympic_record VALUES ('1920', '8', "Greece", 'GRE'); 
INSERT INTO Olympic_record VALUES ('1920', '8', "Luxembourg", 'LUX'); 
INSERT INTO Olympic_record VALUES ('1920', '8', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1920', '999', "Czechoslovakia", 'TCH'); 
INSERT INTO Olympic_record VALUES ('1924', '1', "Uruguay", 'URU'); 
INSERT INTO Olympic_record VALUES ('1924', '2', "Switzerland", 'SUI'); 
INSERT INTO Olympic_record VALUES ('1924', '3', "Sweden", 'SWE'); 
INSERT INTO Olympic_record VALUES ('1924', '4', "Netherlands", 'NED'); 
INSERT INTO Olympic_record VALUES ('1924', '5', "Ireland", 'IRL'); 
INSERT INTO Olympic_record VALUES ('1924', '5', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1924', '5', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1924', '5', "Egypt", 'EGY'); 
INSERT INTO Olympic_record VALUES ('1924', '9', "Romania", 'ROU'); 
INSERT INTO Olympic_record VALUES ('1924', '9', "Bulgaria", 'BUL'); 
INSERT INTO Olympic_record VALUES ('1924', '9', "Latvia", 'LAT'); 
INSERT INTO Olympic_record VALUES ('1924', '9', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1924', '9', "Czechoslovakia", 'TCH'); 
INSERT INTO Olympic_record VALUES ('1924', '9', "Luxembourg", 'LUX'); 
INSERT INTO Olympic_record VALUES ('1924', '9', "Belgium", 'BEL'); 
INSERT INTO Olympic_record VALUES ('1924', '9', "Hungary", 'HUN'); 
INSERT INTO Olympic_record VALUES ('1924', '17', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1924', '17', "Estonia", 'EST'); 
INSERT INTO Olympic_record VALUES ('1924', '17', "Turkey", 'TUR'); 
INSERT INTO Olympic_record VALUES ('1924', '17', "Lithuania", 'LTU'); 
INSERT INTO Olympic_record VALUES ('1924', '17', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('1924', '17', "Poland", 'POL'); 
INSERT INTO Olympic_record VALUES ('1928', '1', "Uruguay", 'URU'); 
INSERT INTO Olympic_record VALUES ('1928', '2', "Argentina", 'ARG'); 
INSERT INTO Olympic_record VALUES ('1928', '3', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1928', '4', "Egypt", 'EGY'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Germany", 'GER'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Belgium", 'BEL'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Portugal", 'POR'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Switzerland", 'SUI'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Netherlands", 'NED'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Mexico", 'MEX'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Luxembourg", 'LUX'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1928', '5', "Turkey", 'TUR'); 
INSERT INTO Olympic_record VALUES ('1928', '17', "Chile", 'CHI'); 
INSERT INTO Olympic_record VALUES ('1936', '1', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1936', '2', "Austria", 'AUT'); 
INSERT INTO Olympic_record VALUES ('1936', '3', "Norway", 'NOR'); 
INSERT INTO Olympic_record VALUES ('1936', '4', "Poland", 'POL'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Great Britain", 'GBR'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Germany", 'GER'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Japan", 'JPN'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Peru", 'PER'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Sweden", 'SWE'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Luxembourg", 'LUX'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Turkey", 'TUR'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Hungary", 'HUN'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "China", 'CHN'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Egypt", 'EGY'); 
INSERT INTO Olympic_record VALUES ('1936', '5', "Finland", 'FIN'); 
INSERT INTO Olympic_record VALUES ('1948', '1', "Sweden", 'SWE'); 
INSERT INTO Olympic_record VALUES ('1948', '2', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1948', '3', "Denmark", 'DEN'); 
INSERT INTO Olympic_record VALUES ('1948', '4', "Great Britain", 'GBR'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "South Korea", 'KOR'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "Turkey", 'TUR'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "Austria", 'AUT'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "China", 'CHN'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "Egypt", 'EGY'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "India", 'IND'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "Luxembourg", 'LUX'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "Mexico", 'MEX'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "Netherlands", 'NED'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "Afghanistan", 'AFG'); 
INSERT INTO Olympic_record VALUES ('1948', '5', "Ireland", 'IRL'); 
INSERT INTO Olympic_record VALUES ('1952', '1', "Hungary", 'HUN'); 
INSERT INTO Olympic_record VALUES ('1952', '2', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1952', '3', "Sweden", 'SWE'); 
INSERT INTO Olympic_record VALUES ('1952', '4', "Germany", 'GER'); 
INSERT INTO Olympic_record VALUES ('1952', '5', "Denmark", 'DEN'); 
INSERT INTO Olympic_record VALUES ('1952', '5', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('1952', '5', "Turkey", 'TUR'); 
INSERT INTO Olympic_record VALUES ('1952', '5', "Austria", 'AUT'); 
INSERT INTO Olympic_record VALUES ('1952', '9', "Soviet Union", 'URS'); 
INSERT INTO Olympic_record VALUES ('1952', '9', "Poland", 'POL'); 
INSERT INTO Olympic_record VALUES ('1952', '9', "Egypt", 'EGY'); 
INSERT INTO Olympic_record VALUES ('1952', '9', "Luxembourg", 'LUX'); 
INSERT INTO Olympic_record VALUES ('1952', '9', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1952', '9', "Netherlands Antilles", 'AHO'); 
INSERT INTO Olympic_record VALUES ('1952', '9', "Norway", 'NOR'); 
INSERT INTO Olympic_record VALUES ('1952', '9', "Finland", 'FIN'); 
INSERT INTO Olympic_record VALUES ('1952', '17', "India", 'IND'); 
INSERT INTO Olympic_record VALUES ('1952', '17', "Bulgaria", 'BUL'); 
INSERT INTO Olympic_record VALUES ('1952', '17', "Greece", 'GRE'); 
INSERT INTO Olympic_record VALUES ('1952', '17', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1952', '17', "Chile", 'CHI'); 
INSERT INTO Olympic_record VALUES ('1952', '17', "Netherlands", 'NED'); 
INSERT INTO Olympic_record VALUES ('1952', '17', "Great Britain", 'GBR'); 
INSERT INTO Olympic_record VALUES ('1952', '17', "Romania", 'ROU'); 
INSERT INTO Olympic_record VALUES ('1952', '17', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1956', '1', "Soviet Union", 'URS'); 
INSERT INTO Olympic_record VALUES ('1956', '2', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1956', '3', "Bulgaria", 'BUL'); 
INSERT INTO Olympic_record VALUES ('1956', '4', "India", 'IND'); 
INSERT INTO Olympic_record VALUES ('1956', '5', "Indonesia", 'INA'); 
INSERT INTO Olympic_record VALUES ('1956', '5', "Great Britain", 'GBR'); 
INSERT INTO Olympic_record VALUES ('1956', '5', "Australia", 'AUS'); 
INSERT INTO Olympic_record VALUES ('1956', '5', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1956', '5', "Germany", 'GER'); 
INSERT INTO Olympic_record VALUES ('1956', '5', "Thailand", 'THA'); 
INSERT INTO Olympic_record VALUES ('1956', '5', "Japan", 'JPN'); 
INSERT INTO Olympic_record VALUES ('1960', '1', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1960', '2', "Denmark", 'DEN'); 
INSERT INTO Olympic_record VALUES ('1960', '3', "Hungary", 'HUN'); 
INSERT INTO Olympic_record VALUES ('1960', '4', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1960', '5', "Bulgaria", 'BUL'); 
INSERT INTO Olympic_record VALUES ('1960', '5', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('1960', '5', "Argentina", 'ARG'); 
INSERT INTO Olympic_record VALUES ('1960', '5', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1960', '9', "Turkey", 'TUR'); 
INSERT INTO Olympic_record VALUES ('1960', '9', "Great Britain", 'GBR'); 
INSERT INTO Olympic_record VALUES ('1960', '9', "Poland", 'POL'); 
INSERT INTO Olympic_record VALUES ('1960', '9', "Peru", 'PER'); 
INSERT INTO Olympic_record VALUES ('1960', '13', "United Arab Republic", 'UAR'); 
INSERT INTO Olympic_record VALUES ('1960', '13', "Chinese Taipei", 'TPE'); 
INSERT INTO Olympic_record VALUES ('1960', '13', "Tunisia", 'TUN'); 
INSERT INTO Olympic_record VALUES ('1960', '13', "India", 'IND'); 
INSERT INTO Olympic_record VALUES ('1964', '1', "Argentina", 'ARG'); 
INSERT INTO Olympic_record VALUES ('1964', '2', "Nigeria", 'NGR'); 
INSERT INTO Olympic_record VALUES ('1964', '3', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('1964', '4', "Belgium", 'BEL'); 
INSERT INTO Olympic_record VALUES ('1964', '5', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1964', '6', "Cote d'Ivoire", 'CIV'); 
INSERT INTO Olympic_record VALUES ('1964', '7', "Netherlands", 'NED'); 
INSERT INTO Olympic_record VALUES ('1964', '8', "Cameroon", 'CMR'); 
INSERT INTO Olympic_record VALUES ('1964', '9', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1964', '10', "South Korea", 'KOR'); 
INSERT INTO Olympic_record VALUES ('1964', '11', "Australia", 'AUS'); 
INSERT INTO Olympic_record VALUES ('1964', '12', "Serbia", 'SRB'); 
INSERT INTO Olympic_record VALUES ('1964', '13', "China", 'CHN'); 
INSERT INTO Olympic_record VALUES ('1964', '14', "New Zealand", 'NZL'); 
INSERT INTO Olympic_record VALUES ('1964', '15', "Japan", 'JPN'); 
INSERT INTO Olympic_record VALUES ('1964', '16', "Honduras", 'HON'); 
INSERT INTO Olympic_record VALUES ('1968', '1', "Hungary", 'HUN'); 
INSERT INTO Olympic_record VALUES ('1968', '2', "Bulgaria", 'BUL'); 
INSERT INTO Olympic_record VALUES ('1968', '3', "Japan", 'JPN'); 
INSERT INTO Olympic_record VALUES ('1968', '4', "Mexico", 'MEX'); 
INSERT INTO Olympic_record VALUES ('1968', '5', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1968', '5', "Guatemala", 'GUA'); 
INSERT INTO Olympic_record VALUES ('1968', '5', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('1968', '5', "Israel", 'ISR'); 
INSERT INTO Olympic_record VALUES ('1968', '9', "Colombia", 'COL'); 
INSERT INTO Olympic_record VALUES ('1968', '9', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('1968', '9', "Ghana", 'GHA'); 
INSERT INTO Olympic_record VALUES ('1968', '9', "Czechoslovakia", 'TCH'); 
INSERT INTO Olympic_record VALUES ('1968', '13', "Guinea", 'GUI'); 
INSERT INTO Olympic_record VALUES ('1968', '13', "Nigeria", 'NGR'); 
INSERT INTO Olympic_record VALUES ('1968', '13', "El Salvador", 'ESA'); 
INSERT INTO Olympic_record VALUES ('1968', '13', "Thailand", 'THA'); 
INSERT INTO Olympic_record VALUES ('1972', '1', "Poland", 'POL'); 
INSERT INTO Olympic_record VALUES ('1972', '2', "Hungary", 'HUN'); 
INSERT INTO Olympic_record VALUES ('1972', '3', "East Germany", 'GDR'); 
INSERT INTO Olympic_record VALUES ('1972', '3', "Soviet Union", 'URS'); 
INSERT INTO Olympic_record VALUES ('1972', '5', "West Germany", 'FRG'); 
INSERT INTO Olympic_record VALUES ('1972', '5', "Denmark", 'DEN'); 
INSERT INTO Olympic_record VALUES ('1972', '7', "Mexico", 'MEX'); 
INSERT INTO Olympic_record VALUES ('1972', '7', "Morocco", 'MAR'); 
INSERT INTO Olympic_record VALUES ('1972', '9', "Malaysia", 'MAS'); 
INSERT INTO Olympic_record VALUES ('1972', '9', "Myanmar", 'MYA'); 
INSERT INTO Olympic_record VALUES ('1972', '9', "Iran", 'IRI'); 
INSERT INTO Olympic_record VALUES ('1972', '9', "Colombia", 'COL'); 
INSERT INTO Olympic_record VALUES ('1972', '13', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1972', '13', "Sudan", 'SUD'); 
INSERT INTO Olympic_record VALUES ('1972', '13', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('1972', '13', "Ghana", 'GHA'); 
INSERT INTO Olympic_record VALUES ('1976', '1', "East Germany", 'GDR'); 
INSERT INTO Olympic_record VALUES ('1976', '2', "Poland", 'POL'); 
INSERT INTO Olympic_record VALUES ('1976', '3', "Soviet Union", 'URS'); 
INSERT INTO Olympic_record VALUES ('1976', '4', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('1976', '5', "Israel", 'ISR'); 
INSERT INTO Olympic_record VALUES ('1976', '5', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1976', '5', "North Korea", 'PRK'); 
INSERT INTO Olympic_record VALUES ('1976', '5', "Iran", 'IRI'); 
INSERT INTO Olympic_record VALUES ('1976', '9', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('1976', '9', "Guatemala", 'GUA'); 
INSERT INTO Olympic_record VALUES ('1976', '9', "Mexico", 'MEX'); 
INSERT INTO Olympic_record VALUES ('1976', '9', "Cuba", 'CUB'); 
INSERT INTO Olympic_record VALUES ('1976', '9', "Canada", 'CAN'); 
INSERT INTO Olympic_record VALUES ('1980', '1', "Czechoslovakia", 'TCH'); 
INSERT INTO Olympic_record VALUES ('1980', '2', "East Germany", 'GDR'); 
INSERT INTO Olympic_record VALUES ('1980', '3', "Soviet Union", 'URS'); 
INSERT INTO Olympic_record VALUES ('1980', '4', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1980', '5', "Kuwait", 'KUW'); 
INSERT INTO Olympic_record VALUES ('1980', '5', "Cuba", 'CUB'); 
INSERT INTO Olympic_record VALUES ('1980', '5', "Iraq", 'IRQ'); 
INSERT INTO Olympic_record VALUES ('1980', '5', "Algeria", 'ALG'); 
INSERT INTO Olympic_record VALUES ('1980', '9', "Venezuela", 'VEN'); 
INSERT INTO Olympic_record VALUES ('1980', '9', "Colombia", 'COL'); 
INSERT INTO Olympic_record VALUES ('1980', '9', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('1980', '9', "Finland", 'FIN'); 
INSERT INTO Olympic_record VALUES ('1980', '13', "Zambia", 'ZAM'); 
INSERT INTO Olympic_record VALUES ('1980', '13', "Nigeria", 'NGR'); 
INSERT INTO Olympic_record VALUES ('1980', '13', "Syria", 'SYR'); 
INSERT INTO Olympic_record VALUES ('1980', '13', "Costa Rica", 'CRC'); 
INSERT INTO Olympic_record VALUES ('1984', '1', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1984', '2', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('1984', '3', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1984', '4', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1984', '5', "Chile", 'CHI'); 
INSERT INTO Olympic_record VALUES ('1984', '5', "Egypt", 'EGY'); 
INSERT INTO Olympic_record VALUES ('1984', '5', "Canada", 'CAN'); 
INSERT INTO Olympic_record VALUES ('1984', '5', "West Germany", 'FRG'); 
INSERT INTO Olympic_record VALUES ('1984', '9', "Norway", 'NOR'); 
INSERT INTO Olympic_record VALUES ('1984', '9', "Cameroon", 'CMR'); 
INSERT INTO Olympic_record VALUES ('1984', '9', "Morocco", 'MAR'); 
INSERT INTO Olympic_record VALUES ('1984', '9', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1984', '13', "Qatar", 'QAT'); 
INSERT INTO Olympic_record VALUES ('1984', '13', "Iraq", 'IRQ'); 
INSERT INTO Olympic_record VALUES ('1984', '13', "Saudi Arabia", 'KSA'); 
INSERT INTO Olympic_record VALUES ('1984', '13', "Costa Rica", 'CRC'); 
INSERT INTO Olympic_record VALUES ('1988', '1', "Soviet Union", 'URS'); 
INSERT INTO Olympic_record VALUES ('1988', '2', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('1988', '3', "West Germany", 'FRG'); 
INSERT INTO Olympic_record VALUES ('1988', '4', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1988', '5', "Sweden", 'SWE'); 
INSERT INTO Olympic_record VALUES ('1988', '5', "Zambia", 'ZAM'); 
INSERT INTO Olympic_record VALUES ('1988', '5', "Australia", 'AUS'); 
INSERT INTO Olympic_record VALUES ('1988', '5', "Argentina", 'ARG'); 
INSERT INTO Olympic_record VALUES ('1988', '9', "Tunisia", 'TUN'); 
INSERT INTO Olympic_record VALUES ('1988', '9', "Iraq", 'IRQ'); 
INSERT INTO Olympic_record VALUES ('1988', '9', "South Korea", 'KOR'); 
INSERT INTO Olympic_record VALUES ('1988', '9', "Yugoslavia", 'YUG'); 
INSERT INTO Olympic_record VALUES ('1988', '13', "China", 'CHN'); 
INSERT INTO Olympic_record VALUES ('1988', '13', "Guatemala", 'GUA'); 
INSERT INTO Olympic_record VALUES ('1988', '13', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1988', '13', "Nigeria", 'NGR'); 
INSERT INTO Olympic_record VALUES ('1992', '1', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('1992', '2', "Poland", 'POL'); 
INSERT INTO Olympic_record VALUES ('1992', '3', "Ghana", 'GHA'); 
INSERT INTO Olympic_record VALUES ('1992', '4', "Australia", 'AUS'); 
INSERT INTO Olympic_record VALUES ('1992', '5', "Sweden", 'SWE'); 
INSERT INTO Olympic_record VALUES ('1992', '6', "Paraguay", 'PAR'); 
INSERT INTO Olympic_record VALUES ('1992', '7', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1992', '8', "Qatar", 'QAT'); 
INSERT INTO Olympic_record VALUES ('1992', '9', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1992', '10', "Mexico", 'MEX'); 
INSERT INTO Olympic_record VALUES ('1992', '11', "South Korea", 'KOR'); 
INSERT INTO Olympic_record VALUES ('1992', '12', "Egypt", 'EGY'); 
INSERT INTO Olympic_record VALUES ('1992', '13', "Denmark", 'DEN'); 
INSERT INTO Olympic_record VALUES ('1992', '14', "Colombia", 'COL'); 
INSERT INTO Olympic_record VALUES ('1992', '15', "Morocco", 'MAR'); 
INSERT INTO Olympic_record VALUES ('1992', '16', "Kuwait", 'KUW'); 
INSERT INTO Olympic_record VALUES ('1996', '1', "Nigeria", 'NGR'); 
INSERT INTO Olympic_record VALUES ('1996', '2', "Argentina", 'ARG'); 
INSERT INTO Olympic_record VALUES ('1996', '3', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('1996', '4', "Portugal", 'POR'); 
INSERT INTO Olympic_record VALUES ('1996', '5', "France", 'FRA'); 
INSERT INTO Olympic_record VALUES ('1996', '6', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('1996', '7', "Mexico", 'MEX'); 
INSERT INTO Olympic_record VALUES ('1996', '8', "Ghana", 'GHA'); 
INSERT INTO Olympic_record VALUES ('1996', '9', "Japan", 'JPN'); 
INSERT INTO Olympic_record VALUES ('1996', '10', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('1996', '11', "South Korea", 'KOR'); 
INSERT INTO Olympic_record VALUES ('1996', '12', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('1996', '13', "Australia", 'AUS'); 
INSERT INTO Olympic_record VALUES ('1996', '14', "Tunisia", 'TUN'); 
INSERT INTO Olympic_record VALUES ('1996', '15', "Saudi Arabia", 'KSA'); 
INSERT INTO Olympic_record VALUES ('1996', '16', "Hungary", 'HUN'); 
INSERT INTO Olympic_record VALUES ('2000', '1', "Cameroon", 'CMR'); 
INSERT INTO Olympic_record VALUES ('2000', '2', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('2000', '3', "Chile", 'CHI'); 
INSERT INTO Olympic_record VALUES ('2000', '4', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('2000', '5', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('2000', '6', "Japan", 'JPN'); 
INSERT INTO Olympic_record VALUES ('2000', '7', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('2000', '8', "Nigeria", 'NGR'); 
INSERT INTO Olympic_record VALUES ('2000', '9', "South Korea", 'KOR'); 
INSERT INTO Olympic_record VALUES ('2000', '10', "Honduras", 'HON'); 
INSERT INTO Olympic_record VALUES ('2000', '11', "South Africa", 'RSA'); 
INSERT INTO Olympic_record VALUES ('2000', '12', "Kuwait", 'KUW'); 
INSERT INTO Olympic_record VALUES ('2000', '13', "Slovakia", 'SVK'); 
INSERT INTO Olympic_record VALUES ('2000', '14', "Czech Republic", 'CZE'); 
INSERT INTO Olympic_record VALUES ('2000', '15', "Australia", 'AUS'); 
INSERT INTO Olympic_record VALUES ('2000', '16', "Morocco", 'MAR'); 
INSERT INTO Olympic_record VALUES ('2004', '1', "Argentina", 'ARG'); 
INSERT INTO Olympic_record VALUES ('2004', '2', "Paraguay", 'PAR'); 
INSERT INTO Olympic_record VALUES ('2004', '3', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('2004', '4', "Iraq", 'IRQ'); 
INSERT INTO Olympic_record VALUES ('2004', '5', "Mali", 'MLI'); 
INSERT INTO Olympic_record VALUES ('2004', '6', "South Korea", 'KOR'); 
INSERT INTO Olympic_record VALUES ('2004', '7', "Australia", 'AUS'); 
INSERT INTO Olympic_record VALUES ('2004', '8', "Costa Rica", 'CRC'); 
INSERT INTO Olympic_record VALUES ('2004', '9', "Ghana", 'GHA'); 
INSERT INTO Olympic_record VALUES ('2004', '10', "Morocco", 'MAR'); 
INSERT INTO Olympic_record VALUES ('2004', '10', "Mexico", 'MEX'); 
INSERT INTO Olympic_record VALUES ('2004', '12', "Tunisia", 'TUN'); 
INSERT INTO Olympic_record VALUES ('2004', '13', "Japan", 'JPN'); 
INSERT INTO Olympic_record VALUES ('2004', '14', "Portugal", 'POR'); 
INSERT INTO Olympic_record VALUES ('2004', '15', "Greece", 'GRE'); 
INSERT INTO Olympic_record VALUES ('2004', '16', "Serbia and Montenegro", 'SCG'); 
INSERT INTO Olympic_record VALUES ('2008', '1', "Argentina", 'ARG'); 
INSERT INTO Olympic_record VALUES ('2008', '2', "Nigeria", 'NGR'); 
INSERT INTO Olympic_record VALUES ('2008', '3', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('2008', '4', "Belgium", 'BEL'); 
INSERT INTO Olympic_record VALUES ('2008', '5', "Italy", 'ITA'); 
INSERT INTO Olympic_record VALUES ('2008', '6', "Cote d'Ivoire", 'CIV'); 
INSERT INTO Olympic_record VALUES ('2008', '7', "Netherlands", 'NED'); 
INSERT INTO Olympic_record VALUES ('2008', '8', "Cameroon", 'CMR'); 
INSERT INTO Olympic_record VALUES ('2008', '9', "United States", 'USA'); 
INSERT INTO Olympic_record VALUES ('2008', '10', "South Korea", 'KOR'); 
INSERT INTO Olympic_record VALUES ('2008', '11', "Australia", 'AUS'); 
INSERT INTO Olympic_record VALUES ('2008', '12', "Serbia", 'SRB'); 
INSERT INTO Olympic_record VALUES ('2008', '13', "China", 'CHN'); 
INSERT INTO Olympic_record VALUES ('2008', '14', "New Zealand", 'NZL'); 
INSERT INTO Olympic_record VALUES ('2008', '15', "Japan", 'JPN'); 
INSERT INTO Olympic_record VALUES ('2008', '16', "Honduras", 'HON'); 
INSERT INTO Olympic_record VALUES ('2012', '1', "Mexico", 'MEX'); 
INSERT INTO Olympic_record VALUES ('2012', '2', "Brazil", 'BRA'); 
INSERT INTO Olympic_record VALUES ('2012', '3', "South Korea", 'KOR'); 
INSERT INTO Olympic_record VALUES ('2012', '4', "Japan", 'JPN'); 
INSERT INTO Olympic_record VALUES ('2012', '5', "Great Britain", 'GBR'); 
INSERT INTO Olympic_record VALUES ('2012', '6', "Senegal", 'SEN'); 
INSERT INTO Olympic_record VALUES ('2012', '7', "Honduras", 'HON'); 
INSERT INTO Olympic_record VALUES ('2012', '8', "Egypt", 'EGY'); 
INSERT INTO Olympic_record VALUES ('2012', '9', "Uruguay", 'URU'); 
INSERT INTO Olympic_record VALUES ('2012', '10', "Belarus", 'BLR'); 
INSERT INTO Olympic_record VALUES ('2012', '11', "Morocco", 'MAR'); 
INSERT INTO Olympic_record VALUES ('2012', '12', "Gabon", 'GAB'); 
INSERT INTO Olympic_record VALUES ('2012', '13', "Switzerland", 'SUI'); 
INSERT INTO Olympic_record VALUES ('2012', '14', "Spain", 'ESP'); 
INSERT INTO Olympic_record VALUES ('2012', '15', "United Arab Emirates", 'UAE'); 
INSERT INTO Olympic_record VALUES ('2012', '16', "New Zealand", 'NZL'); 
